import type { NextPage } from "next";
import Head from "next/head";
import BaseLayout from "../src/layout/BaseLayout";
import { HeroSection } from "../src/website/heroSection/HeroSection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Plantidea | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <HeroSection />
      </BaseLayout>
    </div>
  );
};

export default Home;

{
  /* <BasePage styles={<Heading text="Home" color="#EEEEEE"></Heading>}>
      
</BasePage> */
}
